In [1]:
import tensorflow as tf
print(tf.__version__)

1.15.0


텐서플로 1.X 버전의 코드를 수정하지 않고 텐서플로 2.0에서 실행 가능

텐서플로 1.X 파일에 아래의 코드 2줄을 추가하면 텐서플로 2.0에서 실행 가능

import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

In [2]:
#converttf2.py

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
# 상수 선언
hello = tf.constant('Hello, Tensorflow')
# 세션 시작
sess = tf.Session()
# 세션 실행
print(sess.run(hello))

Instructions for updating:
non-resource variables are not supported in the long term
b'Hello, Tensorflow'


In [3]:
#random01.py

import tensorflow as tf
sess = tf.Session()

# 변수 선언
a = tf.Variable(tf.random_uniform([1])) # 0 ~ 1 사이의 난수 1개 발생
b = tf.Variable(tf.random_uniform([1], 0, 10)) # 0 ~ 10 사이의 난수 1개 발생

# 모든 변수 초기화
sess.run(tf.global_variables_initializer())
print('a=', sess.run(a))
print('b=', sess.run(b))
""" 난수 상수 생성 """

# 정규분포 난수
norm = tf.random_normal([2, 3], mean=-1, stddev=4)
print(sess.run(norm))

# 주어진 값들을 shuffle()함수로 무작위로 섞음
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)
print(sess.run(shuff))

# 균등분포 난수
unif = tf.random_uniform([2,3], minval=0, maxval=3)
print(sess.run(unif))

a= [0.52061677]
b= [8.424455]
[[ 1.8890152   1.0903366   1.2321899 ]
 [-0.76504445 -1.1396103   0.34278548]]
[[1 2]
 [3 4]
 [5 6]]
[[1.1791613  1.0675399  0.00538123]
 [0.76899254 1.1324522  2.8846931 ]]


In [5]:
#placeholder01.py

import tensorflow as tf
# 상수나 변수의 데이터 타입만 설정하고 실행단계에서 딕셔너리에 값을 대입해서 사용할 경우 placeholder 사용

# 실수 자료형 1개를 가진 배열
# 변수 선언
node1 = tf.placeholder(tf.float32)
node2 = tf.placeholder(tf.float32)

# 변수 연산
add = node1 + node2
mul = node1 * node2

# 세션 선언
sess = tf.Session()

# 출력
print(sess.run(add, feed_dict={node1:3, node2:4.0}))
print(sess.run(mul, feed_dict={node1:3, node2:4.0}))

7.0
12.0


In [6]:
#placeholder02.py

import tensorflow as tf

# placeholder 정의
a = tf.placeholder(tf.int32) # 정수 자료형 1개를 가진 배열
b = tf.placeholder(tf.int32) # 정수 자료형 1개를 가진 배열

add = tf.add(a, b)
mul = tf.multiply(a, b)

# Launch the default graph
with tf.Session() as sess:
  print(sess.run(add, feed_dict={a: 2, b: 3}))
  print(sess.run(mul, feed_dict={a: 3, b: 5}))

5
15


In [7]:
#placeholder03.py

import tensorflow as tf

# placeholder 정의
a = tf.placeholder(tf.int32, [3]) # 정수 자료형 3개를 가진 배열

# 배열을 모든 값을 2배하는 연산 정의하기
b = tf.constant(2)
op = a * b

# 세션 시작하기
sess = tf.Session()

# placeholder에 값을 넣고 실행하기
r1 = sess.run(op, feed_dict={ a: [1, 2, 3] })
r2 = sess.run(op, feed_dict={ a: [10, 20, 10] })
print(r1)
print(r2)

[2 4 6]
[20 40 20]


In [8]:
#placeholder04.py

import tensorflow as tf

# placeholder 정의
a = tf.placeholder(tf.int32, [None]) # 배열의 크기를 None으로 지정

# 배열의 모든 값을 10배하는 연산 정의하기
b = tf.constant(10)
op = a * b

# 세션 시작하기
sess = tf.Session()

# placeholder에 값을 넣고 실행하기
r1 = sess.run(op, feed_dict={a: [1,2,3,4,5]})
r2 = sess.run(op, feed_dict={a: [10,20]})
print(r1)
print(r2)

[10 20 30 40 50]
[100 200]


In [10]:
#gradient_descent.py

import tensorflow as tf

# 공부한 시간(x_data) : 2 4 6 8
# 성적(y_data) : 81 93 91 97
x_data = [2, 4, 6, 8] # 공부한 시간
y_data = [81,93,91,97] # 성적

# 기울기 a와 y 젃편 b의 값을 임의로 정함
# 단, 기울기의 범위는 0 ~ 10 사이이며 y 절편은 0 ~ 100 사이에서 변하게 함
# tf.random_normal([1]) : 난수 1개 발생
a = tf.Variable(tf.random_uniform([1], 0, 10, dtype = tf.float64, seed = 0)) # 기울기
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype = tf.float64, seed = 0)) # 절편

# y에 대한 일차 방정식 ( y = ax + b)
y = a * x_data + b

# 텐서플로 cost 구하기
cost = tf.reduce_mean(tf.square( y - y_data ))

# 학습률 값
learning_rate = 0.1

# cost 값을 최소로 하는 값 찾기 : 경사 하강법
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# 텐서플로를 이용한 학습
sess = tf.Session()

# 변수 초기화
sess.run(tf.global_variables_initializer())

# 2001번 실행(0번 째를 포함하므로)
# 2000번 학습
for step in range(2001):
   sess.run(gradient_decent)
   # 100번마다 결과 출력
   if step % 100 == 0:
      print("step: %.f, cost = %.4f, 기울기 a = %.4f, y 절편 b = %.4f" % (step, sess.run(cost), sess.run(a), sess.run(b)))

step: 0, cost = 29348.4665, 기울기 a = -28.2352, y 절편 b = 74.5831
step: 100, cost = 1332833190343361000655520381662764125916604617849245023782993539225952697233047532021541465529928667911505892918858167159602024886095866802603032576.0000, 기울기 a = -6483838871800039086094962846546263238098387308584784871137117992860516352.0000, y 절편 b = -1086511987322886058995192342610079605140090437671876784394836575638257664.0000
step: 200, cost = 60546656861665671273717878384283975907277699381866791502680558998625304314508583454185424633562676570601560598193588414780502103846090405320449112293075066601960711071567411405302442370698522950494985417273991346937109516972304884198175341805770754549203176021295390507802749001424772792320.0000, 기울기 a = -1381940670625259281720238551668281768144137432421629953806554981886639854845698404530537149701282188161364139775542138485990909743464418606317568.0000, y 절편 b = -2315750181476253301184821807102861157487332832794844857171012423981865909236815810407700070868619493

In [12]:
#linear_regression02.py

import tensorflow as tf

# input data
x_train = [ 1, 2, 3]
y_train = [10, 20, 30]

# tf.random_normal([1]) : 난수 1개 발생
W = tf.Variable(tf.random_normal([1]), name='weight') # 기울기, 가중치
b = tf.Variable(tf.random_normal([1]), name='bias') # 절편

# Our hypothesis XW+b
hypothesis = x_train * W + b

# cost/loss function
# square 함수는 제곱의 값
# reduce_mean 함수는 평균
cost = tf.reduce_mean(tf.square(hypothesis - y_train))

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Minimize
# GradientDescentOptimizer 함수는 경사하강법을 구현한 함수임
# 경사는 코스트를 가중치로 미분한 값
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)

# minimize 함수는 최소화핚 결과를 반홖함
train = optimizer.minimize(cost)

# Fit the line
for step in range(2001):
  # 2000번 학습
  sess.run(train)
  if step % 100 == 0:
    print(step, 'cost=',sess.run(cost), 'weight=',sess.run(W), 'bias=',sess.run(b))

# Learns best fit W:[ 1.], b:[ 0.]

0 cost= 421.91605 weight= [0.9847863] bias= [-1.145946]
100 cost= 46.000458 weight= [6.37123] bias= [1.1565725]
200 cost= 5.586846 weight= [8.152671] bias= [1.874834]
300 cost= 1.2152419 weight= [8.752172] bias= [2.0747135]
400 cost= 0.7167538 weight= [8.963921] bias= [2.1055367]
500 cost= 0.63568443 weight= [9.048221] bias= [2.0817745]
600 cost= 0.6007454 weight= [9.090394] bias= [2.040926]
700 cost= 0.5719946 weight= [9.118416] bias= [1.9952626]
800 cost= 0.5450831 weight= [9.141457] bias= [1.9487882]
900 cost= 0.5194877 weight= [9.16254] bias= [1.9027972]
1000 cost= 0.49509847 weight= [9.182661] bias= [1.857695]
1100 cost= 0.4718555 weight= [9.202151] bias= [1.8135971]
1200 cost= 0.44970337 weight= [9.221128] bias= [1.7705251]
1300 cost= 0.42859206 weight= [9.239637] bias= [1.7284696]
1400 cost= 0.40847173 weight= [9.257701] bias= [1.6874108]
1500 cost= 0.38929534 weight= [9.275337] bias= [1.6473264]
1600 cost= 0.3710195 weight= [9.292551] bias= [1.6081939]
1700 cost= 0.35360178 wei

In [13]:
#linear_regression_feed.py (linear regression을 placeholder로 구현)

import tensorflow as tf

# Try to find values for W and b to compute y_data = W * x_data + b
# We know that W should be 1 and b should be 0
W = tf.Variable(tf.random_normal([1]), name='weight') # 기울기
b = tf.Variable(tf.random_normal([1]), name='bias') # 절편

# Now we can use X and Y in place of x_data and y_data
X = tf.placeholder(tf.float32, shape=[None]) # placeholder 정의, 여러 개의 데이터를 받는다!
Y = tf.placeholder(tf.float32, shape=[None])

# Our hypothesis XW+b
hypothesis = X * W + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer()) # 모든 변수를 초기화

#Fit the line
for step in range(2001):
  # 2000번 학습
  cost_val, W_val, b_val, _ = sess.run([cost, W, b, train],feed_dict={X: [1, 2, 3], Y: [1, 2, 3]})
  if step % 20 == 0:
    # print(step, cost_val, W_val, b_val)
    print(step, 'cost=',cost_val, 'weight=',W_val, 'bias=',b_val)
# Learns best fit W:[ 1.], b:[ 0]

0 cost= 4.075312 weight= [0.6445323] bias= [2.5236394]
20 cost= 0.6904714 weight= [0.11884148] bias= [2.1664364]
40 cost= 0.5997994 weight= [0.10860607] bias= [2.0419028]
60 cost= 0.54449993 weight= [0.14558043] bias= [1.9437777]
80 cost= 0.49452147 weight= [0.18526667] bias= [1.8522214]
100 cost= 0.4491321 weight= [0.22351158] bias= [1.7651541]
120 cost= 0.407909 weight= [0.25999942] bias= [1.6821964]
140 cost= 0.37046924 weight= [0.2947764] bias= [1.6031389]
160 cost= 0.33646607 weight= [0.32791936] bias= [1.5277972]
180 cost= 0.305584 weight= [0.3595046] bias= [1.4559965]
200 cost= 0.27753627 weight= [0.38960558] bias= [1.3875699]
220 cost= 0.2520628 weight= [0.41829193] bias= [1.3223592]
240 cost= 0.22892755 weight= [0.44563004] bias= [1.2602131]
260 cost= 0.20791559 weight= [0.4716834] bias= [1.2009877]
280 cost= 0.18883222 weight= [0.49651238] bias= [1.1445457]
300 cost= 0.17150056 weight= [0.5201743] bias= [1.0907563]
320 cost= 0.15575953 weight= [0.5427245] bias= [1.0394948]
34

In [14]:
#multi_linear_regression.py

import tensorflow as tf

# x1, x2, y의 데이터 값
x1 = [2, 4, 6, 8] # 공부핚 시갂
x2 = [0, 4, 2, 3] # 과외 수업 횟수
y_data = [81,93,91,97] # 성적

# 기울기 a와 y젃편 b의 값을 임의로 정함.
# 단 기울기의 범위는 0-10 사이, y 젃편은 0-100사이에서 변하게 함
a1 = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))
a2 = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))

# 새로운 방정식
y = a1 * x1 + a2 * x2 + b

# 텐서플로 RMSE 함수(비용 함수)
rmse = tf.sqrt(tf.reduce_mean(tf.square( y - y_data )))

# 학습률
learning_rate = 0.1

# 경사 하강법으로 RMSE 값(비용)을 최소로 하는 값 찾기
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

# 학습이 진행되는 부분
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  # 모든 변수 초기화
  for step in range(2001):
    # 2000번 학습
    sess.run(gradient_decent)
    if step % 100 == 0:
       print("Epoch: %.f, RMSE = %.4f, 기울기 a1 = %.4f, 기울기 a2 = %.4f, y절편 b = %.4f"%(step, sess.run(rmse), sess.run(a1), sess.run(a2), sess.run(b)))

Epoch: 0, RMSE = 49.1842, 기울기 a1 = 7.5270, 기울기 a2 = 7.8160, y절편 b = 80.5980
Epoch: 100, RMSE = 1.8368, 기울기 a1 = 1.1306, 기울기 a2 = 2.1316, y절편 b = 78.5119
Epoch: 200, RMSE = 1.8370, 기울기 a1 = 1.1879, 기울기 a2 = 2.1487, y절편 b = 78.1057
Epoch: 300, RMSE = 1.8370, 기울기 a1 = 1.2122, 기울기 a2 = 2.1571, y절편 b = 77.9352
Epoch: 400, RMSE = 1.8370, 기울기 a1 = 1.2226, 기울기 a2 = 2.1607, y절편 b = 77.8636
Epoch: 500, RMSE = 1.8370, 기울기 a1 = 1.2269, 기울기 a2 = 2.1622, y절편 b = 77.8335
Epoch: 600, RMSE = 1.8370, 기울기 a1 = 1.2288, 기울기 a2 = 2.1628, y절편 b = 77.8208
Epoch: 700, RMSE = 1.8370, 기울기 a1 = 1.2295, 기울기 a2 = 2.1631, y절편 b = 77.8155
Epoch: 800, RMSE = 1.8370, 기울기 a1 = 1.2299, 기울기 a2 = 2.1632, y절편 b = 77.8133
Epoch: 900, RMSE = 1.8370, 기울기 a1 = 1.2300, 기울기 a2 = 2.1632, y절편 b = 77.8124
Epoch: 1000, RMSE = 1.8370, 기울기 a1 = 1.2301, 기울기 a2 = 2.1633, y절편 b = 77.8120
Epoch: 1100, RMSE = 1.8370, 기울기 a1 = 1.2301, 기울기 a2 = 2.1633, y절편 b = 77.8118
Epoch: 1200, RMSE = 1.8370, 기울기 a1 = 1.2301, 기울기 a2 = 2.1633, y절편 b = 77.81

In [17]:
#multi_linear_regression02.py

import tensorflow as tf

# 학습 데이터
x1_data = [73., 93., 89., 96., 73.] # quiz1
x2_data = [80., 88., 91., 98., 66.] # quiz2
x3_data = [75., 93., 90., 100., 70.] # midterm
y_data = [152., 185., 180., 196., 142.] # final

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32) # placeholder 정의
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function : 비용함수
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00003)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session() # 세션 설정

# Initializes global variables in the graph.
# 모든 변수 초기화
sess.run(tf.global_variables_initializer())

# 10000번 학습
for step in range(10001):
  cost_val, hy_val, _= sess.run([cost, hypothesis, train],
                                feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
  if step % 100 == 0:
    print("step =", step, "Cost: ", cost_val, "Prediction:", hy_val)

step = 0 Cost:  86586.73 Prediction: [ -98.351746 -136.74861  -124.9335   -137.62994  -107.88419 ]
step = 100 Cost:  53.890034 Prediction: [161.7572  177.56206 183.88898 198.76552 132.19429]
step = 200 Cost:  45.84134 Prediction: [160.93736 178.12448 183.63828 198.58032 132.93565]
step = 300 Cost:  39.00068 Prediction: [160.18167 178.64293 183.40721 198.40935 133.61923]
step = 400 Cost:  33.18672 Prediction: [159.48512 179.12082 183.19426 198.25153 134.24957]
step = 500 Cost:  28.245382 Prediction: [158.84312 179.56133 182.998   198.10583 134.83084]
step = 600 Cost:  24.045527 Prediction: [158.25133 179.96736 182.81714 197.97128 135.36684]
step = 700 Cost:  20.475922 Prediction: [157.70589 180.34166 182.65047 197.84706 135.86113]
step = 800 Cost:  17.442074 Prediction: [157.2032  180.68669 182.49692 197.73235 136.31697]
step = 900 Cost:  14.863525 Prediction: [156.73987 181.00467 182.3554  197.62637 136.73734]
step = 1000 Cost:  12.671856 Prediction: [156.31282 181.29778 182.22499 197.

In [20]:
#logistic_regression01.py

import tensorflow as tf

# 학습 데이터
# [ 공부시간, 과외받은 횟수 ]
x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
# 1:합격, 0:불합격
y_data = [[0], 
          [0],
          [0],
          [1],
          [1],
          [1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W))) : 가설, 모델
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function : 비용함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation : 정확도 계산
# True if hypothesis>0.5 else False
# tf.cast()함수는 True면 1, False면 0을 리턴함
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32) # predicted = 1 or 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
   # Initialize TensorFlow variables : 모든 변수 초기화
   sess.run(tf.global_variables_initializer())
   # 10000번 학습
   for step in range(10001):
     cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
     # 200번 마다 출력
     if step % 200 == 0:
       print("step = ", step, "cost =", cost_val)
   # Accuracy report
   h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
   print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

step =  0 cost = 0.5293753
step =  200 cost = 0.43999457
step =  400 cost = 0.4140042
step =  600 cost = 0.39517543
step =  800 cost = 0.3798664
step =  1000 cost = 0.36653242
step =  1200 cost = 0.3544561
step =  1400 cost = 0.34327814
step =  1600 cost = 0.3328046
step =  1800 cost = 0.32292297
step =  2000 cost = 0.313562
step =  2200 cost = 0.30467254
step =  2400 cost = 0.29621747
step =  2600 cost = 0.2881666
step =  2800 cost = 0.28049418
step =  3000 cost = 0.27317718
step =  3200 cost = 0.2661946
step =  3400 cost = 0.25952718
step =  3600 cost = 0.25315675
step =  3800 cost = 0.24706651
step =  4000 cost = 0.24124068
step =  4200 cost = 0.23566441
step =  4400 cost = 0.23032367
step =  4600 cost = 0.2252056
step =  4800 cost = 0.22029774
step =  5000 cost = 0.2155887
step =  5200 cost = 0.21106769
step =  5400 cost = 0.20672464
step =  5600 cost = 0.20255004
step =  5800 cost = 0.19853501
step =  6000 cost = 0.1946712
step =  6200 cost = 0.19095081
step =  6400 cost = 0.18736

In [22]:
#logistic_regression02.py

import tensorflow as tf
import numpy as np

# 실행할 때마다 같은 결과를 출력하기 위핚 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

# 학습 데이터
x_data = np.array([[2, 3],[4, 3],[6, 4],[8, 6],[10, 7],[12, 8],[14, 9]])
y_data = np.array([0, 0, 0, 1, 1, 1,1]).reshape(7, 1)

# 플레이스 홀더 정의
X = tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])

# 기울기 a와 bias b의 값을 임의로 정함.
a = tf.Variable(tf.random_uniform([2,1], dtype=tf.float64)) # 2행 1열의 난수 발생
b = tf.Variable(tf.random_uniform([1], dtype=tf.float64)) # 1개의 난수 발생

# y 시그모이드 함수의 방정식을 세움
y = tf.sigmoid(tf.matmul(X, a) + b)

# 오차를 구하는 함수
loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))

# 학습률 값
learning_rate=0.1

# 경사 하강법으로 오차(비용)를 최소로 하는 값 찾기
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
predicted = tf.cast(y > 0.5, dtype=tf.float64) # tf.cast()함수는 True면 1, Flase면 0을 리턴함
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  # 3000번 학습
  for i in range(3001):
     a_, b_, loss_, _ = sess.run([a, b, loss, gradient_decent], feed_dict={X: x_data, Y: y_data})
     if (i + 1) % 300 == 0:
       print("step = %d, a1 = %.4f, a2 = %.4f, b = %.4f, loss = %.4f" % (i + 1, a_[0], a_[1], b_, loss_))
  # 공부시간, 개인 과외수, 합격 가능성
  new_x = np.array([7, 6]).reshape(1, 2) #[7, 6]은 각각 공부 시갂과 과외 수업수.
  new_y = sess.run(y, feed_dict={X: new_x})
  print("공부 시간: %d, 개인 과외 수: %d" % (new_x[:,0], new_x[:,1]))
  print("합격 가능성: %6.2f %%" % (new_y*100))

step = 300, a1 = 0.8139, a2 = -0.5527, b = -2.4268, loss = 0.2671
step = 600, a1 = 0.8157, a2 = -0.2837, b = -3.8951, loss = 0.1915
step = 900, a1 = 0.7280, a2 = 0.0405, b = -4.9585, loss = 0.1498
step = 1200, a1 = 0.6262, a2 = 0.3444, b = -5.8001, loss = 0.1227
step = 1500, a1 = 0.5286, a2 = 0.6158, b = -6.4982, loss = 0.1036
step = 1800, a1 = 0.4401, a2 = 0.8554, b = -7.0951, loss = 0.0895
step = 2100, a1 = 0.3613, a2 = 1.0672, b = -7.6168, loss = 0.0787
step = 2400, a1 = 0.2915, a2 = 1.2553, b = -8.0803, loss = 0.0702
step = 2700, a1 = 0.2297, a2 = 1.4234, b = -8.4972, loss = 0.0633
step = 3000, a1 = 0.1746, a2 = 1.5747, b = -8.8762, loss = 0.0577
공부 시간: 7, 개인 과외 수: 6
합격 가능성:  85.75 %


In [23]:
#bmi.py
import numpy as np
import pandas as pd
import tensorflow as tf

# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기
csv = pd.read_csv("bmi.csv")

# 데이터 정규화
csv["height"] = csv["height"] / 200
csv["weight"] = csv["weight"] / 100

# 레이블을 배열로 변환
# thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]}
csv["label_pat"] = csv["label"].apply(lambda x : np.array(bclass[x]))

# 플레이스홀더 선언하기
x = tf.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기
y_ = tf.placeholder(tf.float32, [None, 3]) # 정답 레이블 넣기

# 변수 선언하기
W = tf.Variable(tf.zeros([2, 3]));
b = tf.Variable(tf.zeros([3]));

# 소프트맥스 회귀 정의하기
y = tf.nn.softmax(tf.matmul(x, W) + b)

# 비용함수, 경사 하강법 적용
cross_entropy = -tf.reduce_sum(y_ * tf.log(y))
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cross_entropy)

# 정답률 구하기 ( tf.argmax(y,1) : y 값 중에서 가장 큰값의 인덱스 번호를 리턴 )
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32))

# 세션 시작하기
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 모든 변수 초기화하기

# 3500번 학습
for step in range(3500):
  i = (step * 100) % 14000
  rows = csv[1 + i : 1 + i + 100]
  x_pat = rows[["weight","height"]]
  y_ans = list(rows["label_pat"])
  fd = {x: x_pat, y_: y_ans}
  sess.run(train, feed_dict=fd)
  if step % 500 == 0:
    cre = sess.run(cross_entropy, feed_dict=fd)
    acc = sess.run(accuracy, feed_dict={x: x_pat, y_: y_ans})
  print("step = ", step, "cre = ", cre, "acc = ", acc)

# 최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: x_pat, y_: y_ans})
print("정답률 =", acc)

FileNotFoundError: ignored

In [24]:
#softmax_classifier.py

import tensorflow as tf
# 실행결과가 매번 동일하게 출력 되도록 seed를 설정
tf.set_random_seed(777)

# 특징 4가지
x_data = [[1, 2, 1, 1]
          , [2, 1, 3, 2]
          , [3, 1, 3, 4]
          , [4, 1, 5, 5]
          , [1, 7, 5, 5]
          , [1, 2, 5, 6]
          , [1, 6, 6, 6]
          , [1, 7, 7, 7]]

# 분류 3가지, 다중 분류
y_data = [[0, 0, 1]
          , [0, 0, 1]
          , [0, 0, 1]
          , [0, 1, 0]
          , [0, 1, 0]
          , [0, 1, 0]
          , [1, 0, 0]
          , [1, 0, 0]]

X = tf.placeholder("float", [None, 4]) # 4열
Y = tf.placeholder("float", [None, 3]) # 3열

nb_classes = 3

# softmax함수에 입력값: 4 , 출력값: nb_classes=3
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# 경사하강법을 이용해서 cost가 최소가 되도록 학습
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  # 2000번 학습
  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
  print('--------------')

# 경사하강법을 이용해서 cost가 최소가 되도록 학습
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  # 2000번 학습
  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
  print('--------------')
  # Testing & One-hot encoding
  a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
  print(a, sess.run(tf.arg_max(a, 1)))
  print('--------------')
  
  b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
  print(b, sess.run(tf.arg_max(b, 1))) # arg_max()함수 : one-hot-encoding을 맊들어 주는 함수
  print('--------------')
  
  c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
  print(c, sess.run(tf.arg_max(c, 1)))
  print('--------------')
  
  all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
  print(all, sess.run(tf.arg_max(all, 1)))

0 2.2075143
200 0.53052104
400 0.41918337
600 0.32158136
800 0.25144106
1000 0.22609563
1200 0.20546351
1400 0.18822896
1600 0.17360139
1800 0.16102777
2000 0.15010586
--------------
0 2.2075143
200 0.53052104
400 0.41918337
600 0.32158136
800 0.25144106
1000 0.22609563
1200 0.20546351
1400 0.18822896
1600 0.17360139
1800 0.16102777
2000 0.15010586
--------------
[[6.9164871e-03 9.9307764e-01 5.9254453e-06]] [1]
--------------
[[0.83156794 0.15980738 0.0086247 ]] [0]
--------------
[[5.7785408e-09 2.6351376e-04 9.9973649e-01]] [2]
--------------
[[6.9164806e-03 9.9307764e-01 5.9254398e-06]
 [8.3156794e-01 1.5980743e-01 8.6247018e-03]
 [5.7785412e-09 2.6351379e-04 9.9973649e-01]] [1 0 2]


In [0]:
'''
--------------
[[ 1.38904958e-03 9.98601854e-01 9.06129117e-06]] [1] # index번호 1번이 가장 큰값
--------------
[[ 0.93119204 0.06290206 0.0059059 ]] [0] # index번호 0번이 가장 큰값
--------------
[[ 1.27327668e-08 3.34112905e-04 9.99665856e-01]] [2] # index번호 2번이 가장 큰값
--------------
[[ 1.38904958e-03 9.98601854e-01 9.06129117e-06] # index번호 1번이 가장 큰값
[ 9.31192040e-01 6.29020557e-02 5.90589503e-03] # index번호 0번이 가장 큰값
[ 1.27327668e-08 3.34112905e-04 9.99665856e-01]] [1 0 2] # index번호 2번이 가장 큰값
'''