copy from:

https://github.com/dhrim/joongang_2020_03/blob/master/material/deep_learning/dnn_iris_classification.ipynb

# IRIS 데이터 분류

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

In [0]:
!wget https://raw.githubusercontent.com/dhrim/joongang_2020_03/master/material/deep_learning/iris.csv

--2020-03-31 05:25:19--  https://raw.githubusercontent.com/dhrim/joongang_2020_03/master/material/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.66K  --.-KB/s    in 0s      

2020-03-31 05:25:24 (60.7 MB/s) - ‘iris.csv’ saved [2720/2720]



In [0]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [0]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
septal_length    120 non-null float64
septal_width     120 non-null float64
petal_length     120 non-null float64
petal_width      120 non-null float64
setosa           120 non-null int64
versicolor       120 non-null int64
virginica        120 non-null int64
dtypes: float64(4), int64(3)
memory usage: 6.7 KB


In [0]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])
# 하나의 데이터는 7개의 숫자로 되어있음

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [0]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

In [0]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy', # 전체적인 분포만 비슷하면 됨(n개 중 가장 큰 것만 부합하는 걸 선택)(tesorflow에는 없고 keras에만 있음)
              metrics=['accuracy'])

In [0]:
model.fit(train_x, train_y, epochs=200, verbose=0)

In [0]:
loss, acc = model.evaluate(test_x, test_y)

print("loss :", loss)
print("acc :", acc)


1/1 [==============================] - 0s 1ms/step - loss: 0.0956 - accuracy: 1.0000
loss : 0.09560436010360718
acc : 1.0


In [0]:
y_ = model.predict(test_x)
print(y_)
# 값이 세 개씩 나오므로 파싱 필요

# 정답 인덱스 추려내기(numpy) (분류)
print(np.argmax(y_, axis=1))

[[9.75673676e-01 2.43181307e-02 8.27652184e-06]
 [1.03358328e-01 8.50463152e-01 4.61784415e-02]
 [9.43487823e-01 5.64481318e-02 6.40477592e-05]
 [5.72339892e-02 8.94786119e-01 4.79798689e-02]
 [9.63531554e-01 3.64552252e-02 1.31908100e-05]
 [9.85559464e-01 1.44381663e-02 2.33891706e-06]
 [9.87246990e-01 1.27514396e-02 1.53981159e-06]
 [9.86045778e-01 1.39519125e-02 2.34355070e-06]
 [7.71593899e-02 8.86503935e-01 3.63367461e-02]
 [9.65395570e-01 3.45892757e-02 1.51625554e-05]
 [1.29119295e-03 3.10026556e-01 6.88682199e-01]
 [3.00825182e-02 8.51837635e-01 1.18079893e-01]
 [9.66985166e-01 3.30021977e-02 1.26458799e-05]
 [2.14466236e-05 3.69448178e-02 9.63033676e-01]
 [9.48868990e-01 5.11076450e-02 2.34511463e-05]
 [1.35980453e-02 7.04681873e-01 2.81719983e-01]
 [3.71280164e-02 8.83592844e-01 7.92791471e-02]
 [9.63663638e-01 3.63120027e-02 2.44024832e-05]
 [9.79038239e-01 2.09550560e-02 6.77385151e-06]
 [7.57286549e-02 8.75596821e-01 4.86745201e-02]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 

# loss categorical_crossentropy

2가지 crossentropy 사용 방법
- categorical_crossentropy
- sparse_categorical_crossentropy

## categorical_crossentropy
y의 값이 one hot encoding인 경우
```
1,0,0
0,1,0
0,0,1
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어
```

loss 설정
```
model.compile(..., loss='categorical_crossentropy')
```


## sparse_categorical_crossentropy
y의 값이 one hot encoding인 경우
```
0
1
2
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어. 1이 아니라 클래스 수 3
```

loss 설정
```
model.compile(..., loss='sparse_categorical_crossentropy')
```


# iris_dnn with category index

아래의 코드는 iris_dnn_and_optimizer.ipynb의 코드를 기반으로 한다.


In [0]:
!wget https://raw.githubusercontent.com/dhrim/joongang_2020_03/master/material/deep_learning/iris_with_category_index.csv

--2020-03-31 05:33:49--  https://raw.githubusercontent.com/dhrim/joongang_2020_03/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2020-03-31 05:33:49 (51.2 MB/s) - ‘iris_with_category_index.csv’ saved [2218/2218]



In [0]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [0]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [0]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(100, 4)
(100, 1)
(20, 4)
(20, 1)


In [0]:
model = keras.Sequential()
model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

# model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=["accuracy"])
model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"]) # 케라스만 가능한, 인덱스만 출력값, 결과만 보여줌
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)
              


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_7 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 1ms/step - loss: 0.0357 - accuracy: 1.0000
loss= 0.03569107875227928
acc= 1.0


In [0]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.96131778e-01 3.86823341e-03 3.15868651e-11]
 [4.03942540e-03 9.93990541e-01 1.97011232e-03]
 [9.85344827e-01 1.46552175e-02 5.77807302e-10]
 [4.67804261e-04 9.97000754e-01 2.53141974e-03]
 [9.98258293e-01 1.74169242e-03 1.86181851e-11]
 [9.98571396e-01 1.42862194e-03 4.43348483e-12]
 [9.99126375e-01 8.73620331e-04 1.97759647e-12]
 [9.99012232e-01 9.87721258e-04 6.06177868e-12]
 [6.25998434e-03 9.92483199e-01 1.25682098e-03]
 [9.95109022e-01 4.89092106e-03 5.54745833e-11]
 [6.60295598e-07 1.66305855e-01 8.33693504e-01]
 [3.20356601e-04 9.72712219e-01 2.69673578e-02]
 [9.94335115e-01 5.66485338e-03 3.27481514e-11]
 [1.36092615e-09 1.83315948e-02 9.81668413e-01]
 [9.98961568e-01 1.03840395e-03 2.00445927e-11]
 [4.05612118e-05 6.63324654e-01 3.36634725e-01]
 [5.03632938e-04 9.90458965e-01 9.03751608e-03]
 [9.94198799e-01 5.80115151e-03 2.48456394e-10]
 [9.95348871e-01 4.65113902e-03 3.95889432e-11]
 [8.46583629e-04 9.96673584e-01 2.47990061e-03]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 

Regression, 회귀
- 임의의 값 출력하도록.

- y = ax + b
> 오차가 가장 작은 선, 정답인 선, 실제의 a와 b, 원래의 함수를 찾는 것 -> 선형회귀, logistic regression, binary regression, binary classification
>
> (이분 분류, 오차 가장 작은 것을 찾아 함수로)
>
> 노이즈가 없는 것으로 회귀

- 함수를 찾아 함수를 만든다

- define 못하는 함수는?
> overfitting이 발생해도 dnn으로 찾아낼 수 있음

- classification 이외의 것

.

classification, 분류
> 0, 1, 2