In [0]:
import tensorflow as tf
print(tf.__version__)

1.15.0


In [4]:
#constant_operation01.py
import tensorflow as tf
# 상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = a+b
print(a)
print(b)
print(c)
print(a+b)

# 세션 시작
sess = tf.Session()

# 연산 결과 출력
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(a+b))

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(), dtype=int32)
Tensor("add:0", shape=(), dtype=int32)
Tensor("add_1:0", shape=(), dtype=int32)
2
3
5
5


In [5]:
# 상수 정의
 a = tf.constant(2)
 b = tf.constant(3)
 c = tf.constant(4)

 # 상수 연산
 cal1 = a + b * c
 cal2 = (a + b) * c

 # 세션 선언
 sess = tf.Session()
 print(sess.run(cal1))
 print(sess.run(cal2))

14
20


In [7]:
#constant_operation02.py
import tensorflow as tf
# 상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)
# 연산 정의
cal1 = a + b * c
cal2 = (a + b) * c
# 세션 시작
sess = tf.Session()
res1 = sess.run(cal1)
res2 = sess.run(cal2)
print(res1)
print(res2)

14
20


In [8]:
#constant_operation03.py
import tensorflow as tf
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)
node4 = tf.multiply(node1, node2)
sess = tf.Session()
print(sess.run([node1, node2]))
print(sess.run(node3))
print(sess.run(node4))

[3.0, 4.0]
7.0
12.0


In [9]:
#constant_operation04.py
import tensorflow as tf
# initialize two constants
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])
# operations
cal1 = tf.add(x1, x2) # 더하기
cal2 = tf.subtract(x1, x2) # 빼기
cal3 = tf.multiply(x1, x2) # 곱하기
cal4 = tf.divide(x1, x2) # 나누기
# initialize the Session
sess = tf.Session()
# print the result
print(sess.run(cal1))
print(sess.run(cal2))
print(sess.run(cal3))
print(sess.run(cal4))
# close the session
sess.close()

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


Tensorflow의 변수(variable)

 w = tf.Variable(`<initial-value>`, name=`<optional-name>`)

In [10]:
#variable01.py
import tensorflow as tf
v = tf.Variable(50) # v변수의 초기값 50 설정
print(v) #<tf.Variable 'Variable:0' shape=() dtype=int32_ref>
# 모든 변수를 초기화
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) # Session을 통해서 init변수를 실행 시켜야한다.
print('v=', sess.run(v)) # v= 50

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>
v= 50


In [11]:
#variable02.py
import tensorflow as tf
v1 = tf.Variable(50) # v1 변수의 초기값 50
v2 = tf.Variable([1,2,3]) # rank: 1, shape: (3)
v3 = tf.Variable([[1],[2]]) # rank: 2, shape: (2,1)
print('v1=', v1) # v1= <tf.Variable 'Variable:0' shape=() dtype=int32_ref>
print('v2=', v2) # v2= <tf.Variable 'Variable_1:0' shape=(3,) dtype=int32_ref>
print('v3=', v3) # v3= <tf.Variable 'Variable_2:0' shape=(2, 1) dtype=int32_ref>
# 모든 변수를 초기화
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) # Session을 통해서 init변수를 실행 시켜야한다.
print('v1=', sess.run(v1)) # v1= 50
print('v2=', sess.run(v2)) # v2= [1 2 3]
print('v3=', sess.run(v3)) # v3= [[1] [2]]

v1= <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>
v2= <tf.Variable 'Variable_2:0' shape=(3,) dtype=int32_ref>
v3= <tf.Variable 'Variable_3:0' shape=(2, 1) dtype=int32_ref>
v1= 50
v2= [1 2 3]
v3= [[1]
 [2]]


In [12]:
#variable03.py
import tensorflow as tf
x = tf.Variable([[2, 2, 2],[2, 2, 2]]) # rank: 2, shape(2,3) 2행 3열
y = tf.Variable([[3, 3, 3],[3, 3, 3]]) # rank: 2, shape(2,3) 2행 3열
z1 = tf.add(x, y) # 덧셈
z2 = tf.subtract(x, y) # 뺄셈
z3 = tf.multiply(x, y) # 곱셈
z4 = tf.matmul(x, tf.transpose(y)) # matrix 곱셈 (전체 행과 열이 맞아야 함, y를 전치행렬로 바꿈)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(z1))
print(sess.run(z2))
print(sess.run(z3))
print(sess.run(z4))

[[5 5 5]
 [5 5 5]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[6 6 6]
 [6 6 6]]
[[18 18]
 [18 18]]


In [16]:
# 변수 선언
x = tf.Variable([[2, 2, 2], [2, 2, 2]])
y = tf.Variable([[3, 3, 3], [3, 3, 3]])

# 변수 연산
z1 = tf.add(x, y)
z2 = tf.subtract(x, y)
z3 = tf.multiply(x, y)
z4 = tf.divide(x, y)
z5 = tf.matmul(x, tf.transpose(y))

# 세션 선언
sess = tf.Session()

# 모든 변수 초기화
# 출력을 위해서 필요함
sess.run(tf.global_variables_initializer())

# 연산 결과 출력
print(sess.run(z1))
print(sess.run(z2))
print(sess.run(z3))
print(sess.run(z4))
print(sess.run(z5))

[[5 5 5]
 [5 5 5]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[6 6 6]
 [6 6 6]]
[[0.66666667 0.66666667 0.66666667]
 [0.66666667 0.66666667 0.66666667]]
[[18 18]
 [18 18]]


In [18]:
#matrix.py
import tensorflow as tf

# 변수 선언
x = tf.Variable([[3., 3.]]) # shape: (1, 2) 1행 2열
y = tf.Variable([[2.],[2.]]) # shape: (2, 1) 2행 1열
mat = tf.matmul(x, y) # matrix 곱셈

# 변수 초기화
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# 각 변수의 shape 출력
print(x.get_shape()) # shape: (1, 2) 1행 2열
print(y.get_shape()) # shape: (2, 1) 2행 1열
print()

# 각 변수 출력
print('x=', sess.run(x))
print('y=', sess.run(y))
print('mat=', sess.run(mat))


(1, 2)
(2, 1)

x= [[3. 3.]]
y= [[2.]
 [2.]]
mat= [[12.]]


In [19]:
#variable04.py
import tensorflow as tf

# 특별한 기능을 가진 함수
# 변수 선언
v1 = tf.Variable(tf.zeros([2,3])) # [[ 0. 0. 0.] [ 0. 0. 0.]]
v2 = tf.Variable(tf.ones([2,3], tf.int32)) # [[1 1 1] [1 1 1]]
v3 = tf.Variable(tf.zeros_like(tf.ones([2,3]))) # [[ 0. 0. 0.] [ 0. 0. 0.]]
v4 = tf.Variable(tf.fill([2,3], 2)) # [[2 2 2] [2 2 2]]
v5 = tf.Variable(tf.fill([2,3], 2.0)) # [[ 2. 2. 2.] [ 2. 2. 2.]]

"""
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)  # [[0, 0, 0], [0, 0, 0]] with dtype=int32

If dtype of input `tensor` is `float32`, then the output is also of `float32`
tensor = tf.constant([[1.0, 2.0, 3.0], [4, 5, 6]])
tf.zeros_like(tensor)  # [[0., 0., 0.], [0., 0., 0.]] with dtype=floa32

If you want to specify desired dtype of output `tensor`, then specify it in
the op tensor = tf.constant([[1.0, 2.0, 3.0], [4, 5, 6]])
tf.zeros_like(tensor,dtype=tf.int32)  # [[0, 0, 0], [0, 0, 0]] with
dtype=int32
"""


# 모든 변수 초기화
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# 변수 출력
print('v1=', sess.run(v1))
print('v2=', sess.run(v2))
print('v3=', sess.run(v3))
print('v4=', sess.run(v4))
print('v5=', sess.run(v5))

v1= [[0. 0. 0.]
 [0. 0. 0.]]
v2= [[1 1 1]
 [1 1 1]]
v3= [[0. 0. 0.]
 [0. 0. 0.]]
v4= [[2 2 2]
 [2 2 2]]
v5= [[2. 2. 2.]
 [2. 2. 2.]]
